# Generated by Django 4.1.4 on 2023-01-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrationform',
        ),
    ]
